export GITHUB_LOGIN=<YOUR LOGIN>
export GITHUB_PASSWORD=<YOUR PASSWORD>
export GITHUB_USERNAME=<YOUR TARGET REPO USERNAME>
export GITHUB_REPO=<YOUR TARGET REPO>
export GITHUB_TESTING=<SHOULD WE SUBSTITUTE ASSIGNEES?>